package integration.annotation.support;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import org.springframework.boot.test.util.TestPropertyValues;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.core.io.ClassPathResource;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

public class PostgresSQLInitializer
    implements ApplicationContextInitializer<ConfigurableApplicationContext> {

  private static final String POSTGRES_IMAGE = "postgres:17-alpine";

  private static PostgreSQLContainer postgres;

  @Override
  public void initialize(@NotNull final ConfigurableApplicationContext context) {
    if (Objects.isNull(postgres)) {
      postgres =
          new PostgreSQLContainer(DockerImageName.parse(POSTGRES_IMAGE))
              .withDatabaseName("testdb")
              .withUsername("testuser")
              .withPassword("testpass")
              .withInitScript("autogenerated/init-schema.sql");
    }

    if (!postgres.isRunning()) {
      postgres.start();
    }

    applySecurityScripts();

    TestPropertyValues.of(
            // Postgres
            "spring.datasource.url=" + postgres.getJdbcUrl(),
            "spring.datasource.username=" + postgres.getUsername(),
            "spring.datasource.password=" + postgres.getPassword())
        .applyTo(context.getEnvironment());
  }

  private void applySecurityScripts() {
    try (final var connection = postgres.createConnection("")) {
      executeScript(connection, "database/supabase-security-test-roles.sql");
      executeScript(connection, "autogenerated/supabase-security.sql");
    } catch (final Exception exception) {
      throw new IllegalStateException("Could not apply PostgreSQL security scripts", exception);
    }
  }

  private void executeScript(final Connection connection, final String path)
      throws IOException, SQLException {
    final var resource = new ClassPathResource(path);
    final var script = new String(resource.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
    try (final var statement = connection.createStatement()) {
      statement.execute(script);
    }
  }
}
