package integration.annotation.support;

import java.util.Objects;
import org.jetbrains.annotations.NotNull;
import org.springframework.boot.test.util.TestPropertyValues;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.ConfigurableApplicationContext;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

public class PostgresSQLInitializer
    implements ApplicationContextInitializer<ConfigurableApplicationContext> {

  private static final String POSTGRES_IMAGE = "postgres:17-alpine";

  static PostgreSQLContainer<?> postgres;

  @Override
  public void initialize(@NotNull final ConfigurableApplicationContext context) {
    if (Objects.isNull(postgres)) {
      postgres =
          new PostgreSQLContainer<>(DockerImageName.parse(POSTGRES_IMAGE))
              .withDatabaseName("testdb")
              .withUsername("testuser")
              .withPassword("testpass")
              .withInitScript("autogenerated/init-schema.sql");
    }

    if (!postgres.isRunning()) {
      postgres.start();
    }

    TestPropertyValues.of(
            // Postgres
            "spring.datasource.url=" + postgres.getJdbcUrl(),
            "spring.datasource.username=" + postgres.getUsername(),
            "spring.datasource.password=" + postgres.getPassword())
        .applyTo(context.getEnvironment());
  }
}
